달력을 그리기 위한 Date 모델링
rlatnrwjs/SJCalendar pull request #4
Opened 2021-08-12 09:49 UTC by rlatnrwjs

- 해당 월을 그리기 위한 데이터 모델링
- 가공된 데이터(dayList) CollectionView 에 그려봄

2021-08-12 15:18 UTC, jaekanglee commented on calendar/model/CalendarModel.swift
> +        isToday = isToday(day: dateString)
setYearMonth라는 메서드가

isToday를 검사하는게 맞을까요? 
SRP관점에서 isToday가 setYearMonth 년/월을 설정하는데 오늘이야? 를 검사하는게 맞나요?

2021-08-12 15:18 UTC, jaekanglee commented on calendar/model/CalendarModel.swift
> +        getFirstDay(date: dateString)
위와 마찬가지 내용입니다.

2021-08-12 15:20 UTC, jaekanglee commented on calendar/model/CalendarModel.swift
> +        getDayList(dayCount: daysCountInMonth, firstDay: weekdayAdding)
getDateCount 를 구하는 메서드에
getDayList를 호출하는게 맞을까요?

2021-08-12 15:23 UTC, jaekanglee commented on calendar/model/CalendarModel.swift
> +        if 7 - firstDay != 6{
변수와 상수의 연산은 웬만해선 괄호로 묶어주세요
ex (7  - firstDay)

2021-08-12 15:26 UTC, jaekanglee commented on calendar/model/CalendarModel.swift
> +        if 7 - firstDay != 6{
이 코드의 의미는 즉 
firstDay !=1 이 true냐는 걸 알고싶은거 잖아요?
7 -fistDay !=6과 
firstDay !=1 중에 어떤것이 더 직관적으로 이해하기 쉬울까요? 


또 1이라는 의미는 어떤 의미일까요?  보통 
예를들어
월 화 수 목 금 토 일
1   2  3  4  5 6  7
로 인덱싱 되어있다면, 이것을 상수변수로써 네이밍을 달아놓고 

firstDay == monDay 라는 조건을 달아놓으면 
표현하고자 하는 월요일부터 1일이 시작될때 공백없이 어레이가 바로 날짜가 시작된다. 라는 의미를 좀더 직관적으로 알수 있지 않을까요?

2021-08-12 15:27 UTC, jaekanglee commented on calendar/model/CalendarModel.swift
> +            for _ in 1...firstDay-1{
firstDay와 startDay 중에 더 직관적인것을 추후에 써주세용

firstDay가 더 직관적이라면 그대로 두셔도 좋습니다.

2021-08-12 15:29 UTC, jaekanglee commented on calendar/model/CalendarModel.swift
> +        print(days)
로그를 print로 찍는것은 좋겠지만 
아마 이렇게 하면 

로깅이 되게 많은 시스템일때 
이 값이 어떤 메서드 또는 위치에서 찍힌 로그인지 알아보기 어렵겠죠 ?
그렇기 때문에 위치를 표현할 수 있게 
"getDayList : [0,1,2,3,4,5,6,7,8,9~~~]"이런식으로 찍히게 두면 더 좋을 것 같습니다. 

로그를 구성하는 전역 펑션을 하나 두시고, Location과 Data를 인자로 받아 공통적으로 구현할 수 있는 펑션을 하나 두는것도 좋은 방법이겠죠 .
[0,0,0,0,1,2,3,4,5,6,7,8,9] 이런식으로

2021-08-12 15:31 UTC, jaekanglee commented on calendar/ui/CalendarViewController.swift
>          if indexPath.first == 0{
콜렉션 뷰를 그릴때 
row 즉 indexPath가 0일떄와 1일떄로 구분하셨는데,
각 조건문의 내부에 있는 로직들을 펑션으로 분리한뒤 , 이 위치에서는 펑션콜만 있으면  굉장히 깔끔해 지겠죠?

2021-08-12 15:34 UTC, jaekanglee commented on calendar/ui/CalendarViewController.swift
>          }else if indexPath.first == 1{
또한 콜렉션 뷰에서 

내가 각 row를 정의할 때 , 0과 1만 쓰일거라면
상수로써 weekNameViewType=0, dayViewType=1 같은 변수에  담아놓고 

indexPath ==0
indexPath ==1
보다는

indexPath == weekNameViewType,
indexPath == dayViewType,

로 구성하면 코드를 봤을떄 어떤 의미인지 좀더 바로 파악할 수 있지 않을까요?

2021-08-12 15:37 UTC, jaekanglee commented on calendar/ui/CalendarViewController.swift
> +                cell.layer.cornerRadius = ((collectionView.bounds.width) / 7) / 2
이런 코드 같은 경우엔, 타인이 보았을때 왜 7로 나누고 왜 2로 나누지 같은 의미는 코드를 분석해도 알수 없는 경우가 많습니다.
가로 나누기 7에서 /2를 한게 얼마쯤 되는지, 왜 이렇게 한건지
코드로 직관적으로 작성할 수 없다면 이런것은 주석을 달아놓는게 좋을 것 같아요.

2021-08-12 15:38 UTC, jaekanglee requested changes
코멘트에 대한 변경사항 확인 후 PR다시 해주세요 ~

2021-08-16 13:19 UTC, closed without merging

2021-08-16 13:19 UTC, rlatnrwjs commented
수정 후 재 PR